# Generated by Django 3.2 on 2022-09-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='flag',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sale'), ('Feature', 'Feature')], max_length=20, verbose_name='Flag'),
        ),
    ]
