# Generated by Django 4.1.1 on 2022-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='Category/', verbose_name='Image'),
        ),
    ]
